version: '3.7'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es
    environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
  foodtruck:
    build: .
    networks: 
        - elastic
  proxy:
    build:
      context: ./main
      dockerfile: Dockerfile.proxy
      args:
        buildno: 1
    ports:
        - "8080:80"
    networks:
        - elastic
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge