FROM maven:3.6.3-jdk-8 as base
WORKDIR /lavagna
COPY ./project/pom.xml ./pom.xml 
COPY ./project/ /lavagna/
RUN mvn dependency:go-offline
RUN mvn package -Dmaven.test.skip=true
COPY ./entrypoint.sh .
ENTRYPOINT [ "sh", "entrypoint.sh" ]
