version: "3.7"
services: 
    mysql:
        build:
            context: .
            dockerfile: Dockerfile-mysql
            args:
                buildno: 1
        environment:
            - "MYSQL_ROOT_PASSWORD=1234"
            - DB_URL="jdbc:mysql://mysql:3306/lavagna?autoReconnect=true&useSSL=false"
            - "DB_DIALECT=mysql"
            - "DB_USER=root"
            - "DB_PASS=1234"
            - "SPRING_PROFILE=dev"
        volumes: 
            - "sqlvol:/var/lib/mysql"
        networks: 
            - lavagna
    lavagna:
        build:
            context: .
            dockerfile: Dockerfile-maven
            args:
                buildno: 1
        networks: 
            - lavagna
        # ports:
        #     - "8080:8080"
    proxy:
        build:
            context: .
            dockerfile: Dockerfile-proxy
            args:
                buildno: 1
        networks:
            - lavagna
        ports:
            - "80:80"

volumes: 
    sqlvol:
networks:
    lavagna:
        driver: bridge
