FROM maven:3.6.3-jdk-8 as base
WORKDIR /lavagna
COPY ./project/ . 
# RUN mvn dependency:go-offline-Dmaven.test.skip=true
RUN mvn verify 

FROM openjdk:8-jre-alpine
WORKDIR /lavagna
RUN apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
COPY --from=base /lavagna/target /lavagna/target
COPY ./entrypoint.sh .
ENTRYPOINT [ "sh", "entrypoint.sh" ]